version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:ZVVrDbx...
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: weatherdb
      DB_USERNAME: dbmasteruser
      DB_PASSWORD: ^4~52yt)s[]=C,P}KQi%(r15LEj4),VD

  db:
    image: postgres:15
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: dbmasteruser
      POSTGRES_PASSWORD: ^4~52yt)s[]=C,P}KQi%(r15LEj4),VD
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
